FSHOnly: true
canonical: https://gematik.de/fhir/epa-research
version: 1.0.0-rc1
fhirVersion: 4.0.1
dependencies:
  de.gematik.dev.epa.medication: 1.1.0-alpha.4
  de.basisprofil.r4: 1.5.0
  de.gematik.fhir.directory: 0.11.8