FSHOnly: true
canonical: https://gematik.de/fhir/epa-research
version: 0.1.0
fhirVersion: 4.0.1
dependencies:
  de.gematik.dev.epa.medication: 1.1.0-alpha.3
  de.basisprofil.r4: 1.5.0-ballot2
  de.gematik.fhir.directory: 0.11.7