/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application

    kotlin("plugin.serialization") version "2.0.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // kotlin reflect
    implementation(kotlin("reflect"))

    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // HAPI FHIR
    implementation("ca.uhn.hapi.fhir:hapi-fhir-base:6.8.8")
    implementation("ca.uhn.hapi.fhir:hapi-fhir-structures-r4:6.8.8")
    implementation("ca.uhn.hapi.fhir:hapi-fhir-validation:6.8.8")
    implementation("ca.uhn.hapi.fhir:hapi-fhir-validation-resources-r4:6.8.8")

    // Logback
    implementation("ch.qos.logback:logback-classic:1.5.5")

    // jackson yaml
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.14.2")

    // Java Template Engine
    implementation("gg.jte:jte:3.1.12")
    implementation("gg.jte:jte-kotlin:3.1.12")

    // Yaml
    implementation("net.mamoe.yamlkt:yamlkt:0.13.0")

    // Diff utils
    implementation("io.github.java-diff-utils:java-diff-utils:4.12")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "de.gematik.epa.poc.privacy.MainKt"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
